
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321/udp"
    command: python server.py
    networks:
      - app-network
    volumes:
      - /home/kyler/classes/cs_net/project_1/src/
    tty: true
    stdin_open: true

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5900-5999:5900"
    environment:
      - SERVER_ADDR=server
      - DISPLAY=:99
    command: /start.sh
    volumes:
    - /home/kyler/classes/cs_net/project_1/src/

    networks:
      - app-network


networks:
  app-network:
    driver: bridge

